Create DATABASE Sample_db;

-- Create a table
CREATE TABLE salespersons (
salesman_id INT PRIMARY KEY,
name VARCHAR(50),
age INT,
city VARCHAR(50)
);

INSERT INTO salespersons (salesman_id, name, age, city)
VALUES (1, 'John Smith', 28, 'New York'),
(2, 'Emily Wong', 35, 'San Fran'),
(3, 'Tom Lee', 42, 'Seattle'),
(4, 'Lucy Chen', 31, 'LA');

-- Create Table Sales from the Steel data
CREATE TABLE sales (
sale_id INT PRIMARY KEY,
car_id INT,
salesman_id INT,
purchase_date DATE,
FOREIGN KEY (car_id) REFERENCES cars(car_id),
FOREIGN KEY (salesman_id) REFERENCES salespersons(salesman_id)
);

-- Insert data into the table Sales 
INSERT INTO sales (sale_id, car_id, salesman_id, purchase_date)
VALUES (1, 1, 1, '2021-01-01'),
(2, 3, 3, '2021-02-03'),
(3, 2, 2, '2021-02-10'),
(4, 5, 4, '2021-03-01'),
(5, 8, 1, '2021-04-02'),
(6, 2, 1, '2021-05-05'),
(7, 4, 2, '2021-06-07'),
(8, 5, 3, '2021-07-09'),
(9, 2, 4, '2022-01-01'),
(10, 1, 3, '2022-02-03'),
(11, 8, 2, '2022-02-10'),
(12, 7, 2, '2022-03-01'),
(13, 5, 3, '2022-04-02'),
(14, 3, 1, '2022-05-05'),
(15, 5, 4, '2022-06-07'),
(16, 1, 2, '2022-07-09'),
(17, 2, 3, '2023-01-01'),
(18, 6, 3, '2023-02-03'),
(19, 7, 1, '2023-02-10'),
(20, 4, 4, '2023-03-01');

-- PERSON WHO SOLD MOST OF THE CARS IN THE YEAR 2023
SELECT sp.name,sp.city,count(s.salesman_id) AS cars_sold
FROM sales s
JOIN salespersons sp
ON s.salesman_id=sp.salesman_id
WHERE YEAR(s.purchase_date) = '2023'
GROUP BY s.salesman_id, sp.name
ORDER BY cars_sold desc
LIMIT 1;

-- Highgest revenue generated by Employee? 
SELECT sp.name,sp.age,sum(c.cost_$) AS revenue
FROM sales s
JOIN salespersons sp
ON s.salesman_id=sp.salesman_id
JOIN cars c
ON c.car_id = s.car_id
WHERE YEAR(s.purchase_date) = '2022'
GROUP BY s.salesman_id, sp.name
ORDER BY revenue desc
LIMIT 1